# MD013/line-length Line length
MD013: false

# MD014/commands-show-output Dollar signs used before commands without showing output
MD014: false

# MD029/ol-prefix Ordered list item prefix
MD019: false

# MD029/ol-prefix Ordered list item prefix
MD029: false

# MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines
MD031: false

# MD032/blanks-around-lists Lists should be surrounded by blank lines
MD032: false

# MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading
MD036: false

# MD040/fenced-code-language Fenced code blocks should have a language specified
MD040: false

# MD041/first-line-heading/first-line-h1 First line in file should be a top level heading
MD041: false
