{
 "title": "Loki APISIX Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (\r\n  label_replace(\r\n    count_over_time({job=\"apisix\"} |= `$filter` != `/api/v1/test` != `/api/v1/support-chatbot/` | regexp `\"(?P<method>GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS|CONNECT|TRACE) ` | method =~ `.+` [$__auto]),\r\n    \"method\", \"$1\", \"method\", \"(.*)\"\r\n  )\r\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (\r\n  count_over_time({job=\"apisix\"} |= `$filter` != `/api/v1/test` != `/api/v1/support-chatbot/`\r\n  | regexp `HTTP/\\d\\.\\d\" (?P<status>\\d{3}) ` \r\n  | status =~ `.+` | status <= 599 | status >= 199 [$__auto])\r\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (fqdn) (\r\n  count_over_time(\r\n    {job=\"apisix\"} |= `$filter`\r\n    | regexp `.*https?://(?P<fqdn>[^/\" ]+).*`  != `/api/v1/test`  != `/api/v1/support-chatbot/`\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "API Request Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"apisix\"} |= `$filter` != `/api/v1/test` != `/api/v1/support-chatbot/` [$__range]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"apisix\"} |= `$filter` != `/api/v1/test` != `/api/v1/support-chatbot/` | logfmt"
    }
   ]
  }
 ]
}