version: "3"

services:
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.12.0-debian}
    container_name: apisix
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.5.11
    restart: always
    container_name: etcd
    volumes:
      - etcd_data:/bitnami/etcd
      - ./etcd_backup:/backup
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    networks:
      apisix:

  dashboard:
    image: apache/apisix-dashboard:3.0.0-centos
    container_name: apisix-dashboard
    volumes:
      - ./apisix_dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    restart: always
    networks:
      apisix:

  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    container_name: prometheus
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      apisix:

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    restart: always
    volumes:
      - ./loki_conf:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      apisix:

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    restart: always
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./promtail_conf:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      apisix:

  grafana:
    image: grafana/grafana:7.3.7
    restart: always
    volumes:
      - "./grafana_conf/provisioning:/etc/grafana/provisioning"
      - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
      - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      apisix:

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/cert.pem:/etc/nginx/cert.pem:ro
      - ./ssl/key.pem:/etc/nginx/key.pem:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - apisix
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
