#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Use this dockerfile to create a docker image of your apisix local/patched codebase

FROM api7/apisix-runtime:dev AS build

ARG ENABLE_PROXY=false

ENV DEBIAN_FRONTEND noninteractive

# replace the source path with the location of apisix related directories in your host machine
# refer: https://web.archive.org/web/20230604150902/https://www.jamestharpe.com/docker-include-files-outside-build-context/

COPY apisix/apisix /usr/local/apisix/apisix
COPY apisix/conf /usr/local/apisix/conf
COPY apisix/bin/apisix /usr/bin/apisix
COPY apisix/apisix-master-0.rockspec /usr/local/apisix/apisix-master-0.rockspec
COPY apisix/utils/linux-install-luarocks.sh /usr/local/apisix/linux-install-luarocks.sh
COPY debian-dev/docker-entrypoint.sh /docker-entrypoint.sh


WORKDIR /usr/local/apisix

SHELL ["/bin/bash", "-c"]

RUN set -x \
    && DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y libreadline-dev lsb-release libpcre3 libpcre3-dev libldap2-dev libssl-dev perl build-essential \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends wget gnupg ca-certificates

RUN set -x \
    && wget -O - https://openresty.org/package/pubkey.gpg | apt-key add - \
    && wget -O - http://repos.apiseven.com/pubkey.gpg | apt-key add - \
    && echo "deb http://openresty.org/package/debian bullseye openresty" | tee /etc/apt/sources.list.d/openresty.list \
    && echo "deb http://repos.apiseven.com/packages/debian bullseye main" | tee /etc/apt/sources.list.d/apisix.list \
    && DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y apisix-runtime

RUN set -x \
    && (test "${ENABLE_PROXY}" != "true" || /bin/sed -i 's,http://deb.debian.org,http://mirrors.aliyun.com,g' /etc/apt/sources.list) \
    && apt-get -y update --fix-missing \
    && apt-get install -y curl \
        gawk \
        git \
        libldap2-dev \
        liblua5.1-0-dev \
        lua5.1 \
        sudo \
        unzip \
        wget \
        make \
        libssl-dev \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && source "$HOME/.cargo/env" \
    # rust version 1.69.0 required to compile lua-resty-ldap
    && rustup install 1.69.0 \
    && rustup default 1.69.0 \
    && bash ./linux-install-luarocks.sh \
    && luarocks config variables.OPENSSL_INCDIR /usr/include/ \
    && luarocks config variables.PCRE_DIR /usr/local/openresty/pcre \
    && luarocks install apisix-master-0.rockspec --tree=/usr/local/apisix/deps --deps-only \
    && mkdir /usr/local/apisix/logs && touch /usr/local/apisix/logs/error.log && touch /usr/local/apisix/logs/access.log

ENV PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin

EXPOSE 9080 9443


RUN ["chmod", "+x", "/docker-entrypoint.sh"]

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["docker-start"]

STOPSIGNAL SIGQUIT
