name: APISIX Alpine docker Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run
        run: |
          make build-on-alpine
          docker-compose -f ./alpine/docker-compose.yaml up -d
          sleep 30
          docker logs alpine_apisix_1

      - name: Test
        run: |
          curl http://127.0.0.1:9080/apisix/admin/schema/service -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'
          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9080/apisix/admin/schema/service -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1')
          if [ ! $code -eq 200 ]; then
              echo "failed: failed to start APISIX-alpine"
              exit 1
          fi

      - name: Tar Image
        run: |
          make save-alpine-tar

      - name: Upload Image
        uses: actions/upload-artifact@v1
        with:
          name: *.tar
          path: ${{ github.workspace }}/package
        
