name: Push apisix to Docker image
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - redhat
    env:
      APISIX_DOCKER_TAG: 3.3.0-${{ matrix.platform }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and run
        run: |
          make build-on-${{ matrix.platform }}
          docker-compose -f ./compose/docker-compose-release.yaml up -d
          sleep 30
          docker logs compose_apisix_1

      - name: Test route
        run: |
          grep -C 3 '\[error\]' compose/apisix_log/error.log && exit 1

          curl http://127.0.0.1:9180/apisix/admin/routes/1 \
          -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
            {
            "uri": "/get",
            "upstream": {
                "type": "roundrobin",
                "nodes": {
                    "httpbin.org:80": 1
                }
            }
          }'

          result_code=`curl -I -m 10 -o /dev/null -s -w %{http_code} http://127.0.0.1:9080/get`
          if [[ $result_code -ne 200 ]];then
                  printf "result_code: %s\n" "$result_code"
                  exit 125
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push apisix:${{ matrix.os }} image to Docker Hub
        uses: docker/build-push-action@v4
        run: |
          make push-x86-on-redhat
