name: Docker compose CI

on:
  push:
    branches: [ br-action ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use docker-compose
      run: docker-compose -p docker-apisix up -d