name: Docker compose CI

on:
  push:
    branches: [ br-action ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: |
        echo "Hello World!"
    - uses: actions/checkout@v2
    - name: use docker-compose
      run: cd ./example && docker-compose -p docker-apisix up -d
#      run: docker-compose -p docker-apisix up -d
#      run: docker-compose -v
