name: Docker compose CI on windows (not work yet)

on:
  push:
    branches: [ br-action ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: use docker-compose
      run: cd ./example && docker-compose -p docker-apisix up -d
